Multiplayer & ChannelAPI fundamentals
pintheworld/pintheworld pull request #84
Opened 2016-12-26 11:59 UTC by blanche

implement fundamentals of multiplayer, channel API and deployment changes
you can join a game from the home screen another player has created and not started yet (e.g. not made a guess yet)
guesses from other players are then pushed to all clients to

please do not just approve this request but test it, there were a lot of merge errors

EVERYBODY MUST READ:
- for this to work, the game has to be deployed on the python server, as it will be in production
- in js-src, run `npm run dev-build`, this will create the sources to /python-src/webapp and keep it up to date as with the dev server
- run the python server as usual, calling http://localhost:8081/ will then be the url of the frontend AND the backend (with /api/)

missing:
- make join game an extra step in the workflow between create player and game (as discussed in meeting before the holidays)
- other guesses are currently only shown in console - display them on the map
- tons of error handling
- make it pretty
- synchronise players always playing in the same round (especially when displaying the highscore)

to play:
- create a game as usual, but don't make a guess yet!
- as player 2 (second browser), search for games on the home screen and join
- you should now play the same cities
- watch the console to see what other guesses the player made

i disabled the game countdown, because player 1 has to wait for player 2 to join and the countdown would make this kind of stressful

2016-12-27 13:00 UTC, andreaseliasson commented on python-src/resources.py
> +from google.appengine.api.channel import channel
Do we need to install a package here, and if so which one?

2016-12-27 13:47 UTC, andreaseliasson commented on python-src/resources.py
> +from google.appengine.api.channel import channel
I tried pip installing the `google-api-python-client` and I now have this in my lib folder.

<img width="305" alt="screen shot 2016-12-27 at 14 39 53" src="https://cloud.githubusercontent.com/assets/7635284/21500774/8877ec76-cc42-11e6-871c-83d187fb7d1b.png">

What am I missing here? (I can't import `google.appengine.api.channel`)

2016-12-27 14:46 UTC, blanche commented
This should be included in the python gae sdk, I didn't install anything additionally 

On 27 December 2016 14:47:08 CET, Andreas Eliasson <notifications@github.com> wrote:
>andreaseliasson commented on this pull request.
>
>
>
>> @@ -1,6 +1,8 @@
> import datetime
> import random
> 
>+from google.appengine.api.channel import channel
>
>I tried pip installing the `google-api-python-client` and I now have
>this in my lib folder.
>
><img width="305" alt="screen shot 2016-12-27 at 14 39 53"
>src="https://cloud.githubusercontent.com/assets/7635284/21500774/8877ec76-cc42-11e6-871c-83d187fb7d1b.png">
>
>What am I missing here? (I can't import `google.appengine.api.channel`)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pintheworld/pintheworld/pull/84

2016-12-27 21:54 UTC, blanche commented on python-src/resources.py
> +from google.appengine.api.channel import channel
Did you manage to get it work? We can make a quick session tomorrow morning if you are free

2016-12-28 10:16 UTC, andreaseliasson commented on python-src/resources.py
> +from google.appengine.api.channel import channel
Yes, I was able to get it working 👍

2016-12-28 10:21 UTC, andreaseliasson commented on python-src/webapp
> +/home/lukas/uni/pintheworld/js-src/dist
Should we remove this folder from git? Running `npm run build-dev` throws an exception the first time. Removing the this folder and running `npm run build-dev` fixes the problem.

2016-12-28 12:16 UTC, andreaseliasson requested changes
Should address what to do with the `python-src/webapp` dir.

2016-12-28 12:24 UTC, andreaseliasson reviewed
Playing multi-player works for me.

2016-12-29 14:41 UTC, andreaseliasson approved these changes

2016-12-29 14:50 UTC, merged

2016-12-30 17:56 UTC, JaneJiangHH commented on js-src/src/app/map.component.js
> +                self.markers.push({lat: currentCity.lat, lng: currentCity.long});
What is this line of code used for? markers is used to push marker where player clicked; cityMarkers is to push the right marker where the city is.